// packages/store/src/lit/create-store.ts
import type { Context } from '@lit/context';
import type { ReactiveControllerHost, ReactiveElement } from '@lit/reactive-element';
import type { Constructor } from '@videojs/utils/types';
import type { TasksRecord } from '../core/queue';
import type { AnySlice, UnionSliceRequests, UnionSliceState, UnionSliceTarget, UnionSliceTasks } from '../core/slice';
import type { StoreConfig, StoreConsumer, StoreProvider } from '../core/store';

import { createContext } from '@lit/context';

import { Store } from '../core/store';
import {
  RequestController as RequestControllerBase,
  SelectorController as SelectorControllerBase,
  TasksController as TasksControllerBase,
} from './controllers';
import { createStoreAttachMixin, createStoreMixin, createStoreProviderMixin } from './mixins';

export const contextKey = Symbol('@videojs/store');

export interface CreateStoreConfig<Slices extends AnySlice[]> extends StoreConfig<UnionSliceTarget<Slices>, Slices> {}

export type CreateStoreHost = ReactiveControllerHost & HTMLElement;

export interface CreateStoreResult<Slices extends AnySlice[]> {
  /**
   * Combined mixin: provides store via context AND auto-attaches slotted media.
   *
   * @example
   * ```ts
   * class MyPlayer extends StoreMixin(LitElement) {}
   * ```
   */
  StoreMixin: <T extends Constructor<ReactiveElement>>(Base: T) => T & Constructor<StoreProvider<Slices>>;

  /**
   * Mixin that provides store via context (no auto-attach).
   *
   * Use when you need granular control over store provisioning.
   *
   * @example
   * ```ts
   * class MyProvider extends StoreProviderMixin(LitElement) {}
   * ```
   */
  StoreProviderMixin: <T extends Constructor<ReactiveElement>>(Base: T) => T & Constructor<StoreProvider<Slices>>;

  /**
   * Mixin that auto-attaches slotted media elements (requires store from context).
   *
   * Use when inheriting store from a parent provider.
   *
   * @example
   * ```ts
   * class MyControls extends StoreAttachMixin(LitElement) {}
   * ```
   */
  StoreAttachMixin: <T extends Constructor<ReactiveElement>>(Base: T) => T & Constructor<StoreConsumer<Slices>>;

  /**
   * Context for consuming store in controllers.
   *
   * Use this with Lit's `ContextConsumer` or the `@consume` decorator.
   *
   * @example
   * ```ts
   * class MyElement extends LitElement {
   *   @consume({ context, subscribe: true })
   *   readonly store!: ContextType<typeof context>;
   * }
   * ```
   */
  context: Context<typeof contextKey, Store<UnionSliceTarget<Slices>, Slices>>;

  /**
   * Creates a store instance for imperative access.
   *
   * Useful for creating a store before rendering or for testing.
   *
   * @example
   * ```ts
   * const store = create();
   * store.attach(videoElement);
   * ```
   */
  create: () => Store<UnionSliceTarget<Slices>, Slices>;

  /**
   * Selector controller bound to this store's context.
   * Subscribes to a selected portion of store state.
   *
   * @example
   * ```ts
   * const { SelectorController } = createStore({ slices: [playbackSlice] });
   *
   * class MyElement extends LitElement {
   *   #paused = new SelectorController(this, s => s.paused);
   *
   *   render() {
   *     return html`<button>${this.#paused.value ? 'Play' : 'Pause'}</button>`;
   *   }
   * }
   * ```
   */
  SelectorController: new <Value>(
    host: CreateStoreHost,
    selector: (state: UnionSliceState<Slices>) => Value
  ) => SelectorControllerBase<Store<UnionSliceTarget<Slices>, Slices>, Value>;

  /**
   * Request controller bound to this store's context.
   * Provides access to a store request by name.
   *
   * @example
   * ```ts
   * const { RequestController } = createStore({ slices: [playbackSlice] });
   *
   * class MyElement extends LitElement {
   *   #play = new RequestController(this, 'play');
   *
   *   render() {
   *     return html`<button @click=${() => this.#play.value()}>Play</button>`;
   *   }
   * }
   * ```
   */
  RequestController: new <Name extends keyof UnionSliceRequests<Slices>>(
    host: CreateStoreHost,
    name: Name
  ) => RequestControllerBase<Store<UnionSliceTarget<Slices>, Slices>, Name>;

  /**
   * Tasks controller bound to this store's context.
   * Subscribes to task state changes.
   *
   * @example
   * ```ts
   * const { TasksController } = createStore({ slices: [playbackSlice] });
   *
   * class MyElement extends LitElement {
   *   #tasks = new TasksController(this);
   *
   *   render() {
   *     const playTask = this.#tasks.value.play;
   *     return html`<button ?disabled=${playTask?.status === 'pending'}>Play</button>`;
   *   }
   * }
   * ```
   */
  TasksController: new (host: CreateStoreHost) => {
    value: TasksRecord<UnionSliceTasks<Slices>>;
    hostConnected: () => void;
    hostDisconnected: () => void;
  };
}

/**
 * Creates a store factory that returns mixins, context, bound controllers, and a create function.
 *
 * @param config - Store configuration including slices and optional lifecycle hooks
 * @returns An object containing mixins, context, bound controllers, and create function
 *
 * @example
 * ```ts
 * import { createStore } from '@videojs/store/lit';
 * import { playbackSlice } from '@videojs/core/dom';
 *
 * const { StoreMixin, SelectorController } = createStore({
 *   slices: [playbackSlice],
 * });
 *
 * // Create a player element with store
 * class MyPlayer extends StoreMixin(LitElement) {}
 *
 * // Create a control element that uses the store via context
 * class MyControl extends LitElement {
 *   #paused = new SelectorController(this, s => s.paused);
 *
 *   render() {
 *     return html`<span>${this.#paused.value ? 'Paused' : 'Playing'}</span>`;
 *   }
 * }
 *
 * customElements.define('my-player', MyPlayer);
 * customElements.define('my-control', MyControl);
 * ```
 *
 * @example
 * ```html
 * <my-player>
 *   <video src="video.mp4"></video>
 *   <my-control></my-control>
 * </my-player>
 * ```
 */
export function createStore<Slices extends AnySlice[]>(config: CreateStoreConfig<Slices>): CreateStoreResult<Slices> {
  type Target = UnionSliceTarget<Slices>;
  type State = UnionSliceState<Slices>;
  type Requests = UnionSliceRequests<Slices>;
  type ProvidedStore = Store<Target, Slices>;

  const context = createContext<ProvidedStore, typeof contextKey>(contextKey);

  function create(): ProvidedStore {
    return new Store(config);
  }

  const StoreProviderMixin = createStoreProviderMixin<Slices>(context, create);
  const StoreAttachMixin = createStoreAttachMixin<Slices>(context);
  const StoreMixin = createStoreMixin<Slices>(context, create);

  // Bound controllers - context is pre-bound
  class SelectorController<Value> extends SelectorControllerBase<ProvidedStore, Value> {
    constructor(host: CreateStoreHost, selector: (state: State) => Value) {
      super(host, context, selector);
    }
  }

  class RequestController<Name extends keyof Requests> extends RequestControllerBase<ProvidedStore, Name> {
    constructor(host: CreateStoreHost, name: Name) {
      super(host, context, name);
    }
  }

  class TasksController extends TasksControllerBase<ProvidedStore> {
    constructor(host: CreateStoreHost) {
      super(host, context);
    }
  }

  return {
    StoreMixin,
    StoreProviderMixin,
    StoreAttachMixin,
    context,
    create,
    SelectorController,
    RequestController,
    TasksController,
  };
}

// packages/store/src/react/create-store.tsx
import type { FC, ReactNode } from 'react';
import type { TasksRecord } from '../core/queue';
import type { AnySlice, UnionSliceRequests, UnionSliceState, UnionSliceTarget, UnionSliceTasks } from '../core/slice';
import type { StoreConfig } from '../core/store';

import { isNull, isUndefined } from '@videojs/utils/predicate';

import { useEffect, useState } from 'react';

import { Store } from '../core/store';
import { StoreContextProvider, useParentStore, useStoreContext } from './context';
import { useRequest as useRequestBase, useSelector as useSelectorBase, useTasks as useTasksBase } from './hooks';

// ----------------------------------------
// Types
// ----------------------------------------

/**
 * Configuration for `createStore`.
 */
export interface CreateStoreConfig<Slices extends AnySlice[]> extends StoreConfig<UnionSliceTarget<Slices>, Slices> {
  /**
   * Display name for React DevTools.
   */
  displayName?: string;
}

/**
 * Props for the Provider component returned by `createStore`.
 */
export interface ProviderProps<Slices extends AnySlice[]> {
  children: ReactNode;
  /**
   * Optional pre-created store instance.
   * If provided, the Provider will use this store instead of creating one.
   * The Provider will NOT destroy this store on unmount.
   */
  store?: Store<UnionSliceTarget<Slices>, Slices>;
  /**
   * If true, inherits the store from a parent Provider context instead of creating a new one.
   * Useful when wrapping a skin with your own Provider to add custom hooks.
   * Defaults to false (isolated store).
   */
  inherit?: boolean;
}

/**
 * Result of `createStore`.
 */
export interface CreateStoreResult<Slices extends AnySlice[]> {
  /**
   * Provider component that creates and manages the store lifecycle.
   */
  Provider: FC<ProviderProps<Slices>>;

  /**
   * Returns the typed store instance from context.
   */
  useStore: () => Store<UnionSliceTarget<Slices>, Slices>;

  /**
   * Subscribes to a selected portion of state.
   * Re-renders only when the selected value changes.
   */
  useSelector: <T>(selector: (state: UnionSliceState<Slices>) => T) => T;

  /**
   * Returns the request map or a selected request.
   */
  useRequest: {
    (): UnionSliceRequests<Slices>;
    <T>(selector: (requests: UnionSliceRequests<Slices>) => T): T;
  };

  /**
   * Subscribes to task state changes.
   * Returns the current tasks map from the queue.
   */
  useTasks: () => TasksRecord<UnionSliceTasks<Slices>>;

  /**
   * Creates a new store instance.
   * Useful for imperative access or creating a store before render.
   */
  create: () => Store<UnionSliceTarget<Slices>, Slices>;
}

// ----------------------------------------
// Implementation
// ----------------------------------------

/**
 * Creates a store factory that returns a Provider and typed hooks.
 *
 * @param config - Store configuration including slices and optional lifecycle hooks
 * @returns An object containing Provider, hooks, and a create function
 *
 * @example
 * ```tsx
 * const { Provider, useStore, useSelector, useRequest, useTasks, create } = createStore({
 *   slices: [playbackSlice, presentationSlice],
 * });
 *
 * function App() {
 *   return (
 *     <Provider>
 *       <Video />
 *       <Controls />
 *     </Provider>
 *   );
 * }
 *
 * function Controls() {
 *   const paused = useSelector((s) => s.paused);
 *   const play = useRequest((r) => r.play);
 *   return <button onClick={() => play()}>{paused ? 'Play' : 'Pause'}</button>;
 * }
 * ```
 */
export function createStore<Slices extends AnySlice[]>(config: CreateStoreConfig<Slices>): CreateStoreResult<Slices> {
  type Target = UnionSliceTarget<Slices>;
  type State = UnionSliceState<Slices>;
  type Requests = UnionSliceRequests<Slices>;
  type Tasks = UnionSliceTasks<Slices>;
  type StoreType = Store<Target, Slices>;

  /**
   * Creates a new store instance.
   */
  function create(): StoreType {
    return new Store(config);
  }

  /**
   * Provider component that manages store lifecycle.
   *
   * Resolution order:
   * 1. If `store` prop provided, uses that store (no cleanup on unmount)
   * 2. If `inherit={true}` and parent store exists, uses parent store (no cleanup)
   * 3. Otherwise, creates a new store and destroys it on unmount
   */
  function Provider({ children, store: providedStore, inherit = false }: ProviderProps<Slices>): ReactNode {
    const parentStore = useParentStore();
    const shouldInherit = inherit && !isNull(parentStore);

    const [store] = useState<StoreType>(() => {
      if (!isUndefined(providedStore)) {
        return providedStore;
      }

      if (shouldInherit) {
        return parentStore as StoreType;
      }

      return create();
    });

    // Only destroy if we created the store (not provided, not inherited)
    const isOwner = isUndefined(providedStore) && !shouldInherit;

    useEffect(() => {
      if (isOwner) {
        return () => store.destroy();
      }

      return undefined;
    }, [store, isOwner]);

    return <StoreContextProvider store={store}>{children}</StoreContextProvider>;
  }

  // Set display name for React DevTools
  if (config.displayName) {
    Provider.displayName = `${config.displayName}.Provider`;
  }

  /**
   * Returns the typed store instance from context.
   */
  function useStore(): StoreType {
    return useStoreContext() as StoreType;
  }

  /**
   * Subscribes to a selected portion of state.
   */
  function useSelector<T>(selector: (state: State) => T): T {
    const store = useStore();
    return useSelectorBase(store, selector);
  }

  /**
   * Returns the request map or a selected request.
   */
  function useRequest(): Requests;
  function useRequest<T>(selector: (requests: Requests) => T): T;
  function useRequest<T>(selector?: (requests: Requests) => T): Requests | T {
    const store = useStore();
    // useRequestBase doesn't use React hooks internally, but we always call it
    // to maintain consistent hook call order (even though it's technically not required)
    const requests = useRequestBase(store) as Requests;

    if (isUndefined(selector)) {
      return requests;
    }

    return selector(requests);
  }

  /**
   * Subscribes to task state changes.
   */
  function useTasks(): TasksRecord<Tasks> {
    const store = useStore();
    return useTasksBase(store) as TasksRecord<Tasks>;
  }

  return {
    Provider,
    useStore,
    useSelector,
    useRequest: useRequest as CreateStoreResult<Slices>['useRequest'],
    useTasks,
    create,
  };
}
